package com.sistemaventa.UI.Gerencia;

import com.sistemaventa.UI.Perfil;
import com.sistemaventa.consultas.CategConsul;
import com.sistemaventa.consultas.ProductConsul;
import com.sistemaventa.consultas.UserConsul;
import com.sistemaventa.objects.ManejadorTable;
import com.sistemaventa.objects.Producto;
import com.sistemaventa.objects.Usuario;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author elvis_agui
 */
public class VentanaPrincipalG extends javax.swing.JFrame {

    private Usuario user;
    private Producto producto = null;
    private Perfil vtnPerfil = null;
    private FormularioNP vtnAdminPerfiles = null;
    private UserConsul userConsul;
    private CategConsul categoriaConsul;
    private ProductConsul productoConsul;
    private ManejadorTable manejador;
    private FormularioNC formulNC = null;
    private int coeficienteAgotamiento = 15;

    public VentanaPrincipalG(Usuario user, UserConsul userConsul) {
        this.user = user;
        this.productoConsul = new ProductConsul();
        this.userConsul = userConsul;
        this.categoriaConsul = new CategConsul();
        this.manejador = new ManejadorTable();
        initComponents();
        this.manejador.manejadorAgotados(productoConsul.productosAgotados(coeficienteAgotamiento), jTableAgotados);
        this.soloNumDecimal(preciojTextField);
        this.soloNumDecimal(precioEditojTextField);
        this.soloNum(unidadesjTextField);
        this.soloNum(coeficientejTextField);
        this.soloNum(cantidadEdtionjTextField);
        coeficientejTextField.setText(coeficienteAgotamiento + "");
        categoriaConsul.getCategoriasDB();
        categoriaConsul.enlistarCategorias(CategoriasjComboBox, "Categorias");
        categoriaConsul.enlistarCategorias(categoriaOrdenjComboBox, "Todos");
        categoriaConsul.enlistarCategorias(categoriaAgregarjComboBox);
        manejador.manejoInventarioProductos(productoConsul.listaProductos(true, true), InvetarioPjTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAgotados = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        coeficientejTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelOpciones = new javax.swing.JPanel();
        jTabbedOtions = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombrePjTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        descjTextArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        preciojTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        unidadesjTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButtonRegistrar = new javax.swing.JButton();
        CategoriasjComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButtonNewCategoria = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        InvetarioPjTable = new javax.swing.JTable();
        busquedajTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        categoriaOrdenjComboBox = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        desAscjComboBox = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        nameEditionjTextField = new javax.swing.JTextField();
        cantidadEdtionjTextField = new javax.swing.JTextField();
        precioEditojTextField = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        descripEditonjTextArea = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        categoriasProductojComboBox = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        categoriaAgregarjComboBox = new javax.swing.JComboBox<>();
        agregarCatejButton = new javax.swing.JButton();
        actulizarProjButton = new javax.swing.JButton();
        eliminarCatjButton = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTableAgotados.setBackground(new java.awt.Color(0, 204, 153));
        jTableAgotados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableAgotados.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTableAgotados.setForeground(new java.awt.Color(0, 0, 0));
        jTableAgotados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableAgotados.setEnabled(false);
        jTableAgotados.setGridColor(new java.awt.Color(0, 0, 0));
        jTableAgotados.setRowHeight(20);
        jTableAgotados.setRowMargin(2);
        jTableAgotados.setSelectionForeground(new java.awt.Color(0, 255, 204));
        jScrollPane1.setViewportView(jTableAgotados);

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Coeficiente de Agotamiento");

        coeficientejTextField.setBackground(new java.awt.Color(0, 204, 204));
        coeficientejTextField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        coeficientejTextField.setForeground(new java.awt.Color(0, 0, 0));

        jButton1.setText("refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coeficientejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coeficientejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(797, 69, 480, 600));

        jPanel3.setBackground(new java.awt.Color(0, 51, 255));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Productos agotados");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 300, 50));

        panelOpciones.setBackground(new java.awt.Color(0, 204, 204));

        jTabbedOtions.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedOtions.setForeground(new java.awt.Color(153, 153, 153));

        jPanel5.setBackground(new java.awt.Color(102, 255, 255));
        jPanel5.setForeground(new java.awt.Color(0, 51, 255));

        jPanel4.setBackground(new java.awt.Color(51, 102, 255));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Formulario para Registrar un nuevo Producto");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nombre de Producto");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        nombrePjTextField.setBackground(new java.awt.Color(204, 255, 255));
        nombrePjTextField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nombrePjTextField.setForeground(new java.awt.Color(0, 0, 0));
        nombrePjTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        descjTextArea.setBackground(new java.awt.Color(204, 255, 255));
        descjTextArea.setColumns(20);
        descjTextArea.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        descjTextArea.setForeground(new java.awt.Color(0, 0, 0));
        descjTextArea.setRows(5);
        jScrollPane2.setViewportView(descjTextArea);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Precio Unitario del Producto Q.");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        preciojTextField.setBackground(new java.awt.Color(204, 255, 255));
        preciojTextField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        preciojTextField.setForeground(new java.awt.Color(0, 0, 0));
        preciojTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        preciojTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preciojTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Unidades Existentes (no decimal)");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        unidadesjTextField.setBackground(new java.awt.Color(204, 255, 255));
        unidadesjTextField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        unidadesjTextField.setForeground(new java.awt.Color(0, 0, 0));
        unidadesjTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Descripcion de Producto(opcional)");
        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonRegistrar.setBackground(new java.awt.Color(51, 51, 255));
        jButtonRegistrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonRegistrar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        CategoriasjComboBox.setBackground(new java.awt.Color(204, 255, 255));
        CategoriasjComboBox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CategoriasjComboBox.setForeground(new java.awt.Color(0, 0, 0));
        CategoriasjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Categorias" }));
        CategoriasjComboBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Categoria del Producto");
        jLabel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel7.setBackground(new java.awt.Color(0, 102, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Nota: El nombre del producto no puede repetirse con productos ya existentes, llenar campos obligatorios");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jButtonNewCategoria.setBackground(new java.awt.Color(0, 102, 255));
        jButtonNewCategoria.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonNewCategoria.setForeground(new java.awt.Color(0, 0, 0));
        jButtonNewCategoria.setText("Nueva Categoria");
        jButtonNewCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(CategoriasjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(preciojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(nombrePjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(unidadesjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(117, 117, 117))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93))))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(139, 139, 139))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jButtonNewCategoria)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombrePjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unidadesjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(preciojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CategoriasjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jButtonNewCategoria)
                .addGap(68, 68, 68)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedOtions.addTab("Nuevo Producto", jPanel5);

        jPanel6.setBackground(new java.awt.Color(0, 204, 204));

        InvetarioPjTable.setBackground(new java.awt.Color(0, 204, 204));
        InvetarioPjTable.setBorder(new javax.swing.border.MatteBorder(null));
        InvetarioPjTable.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        InvetarioPjTable.setForeground(new java.awt.Color(0, 0, 0));
        InvetarioPjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        InvetarioPjTable.setEnabled(false);
        InvetarioPjTable.setGridColor(new java.awt.Color(0, 0, 0));
        InvetarioPjTable.setRowHeight(30);
        InvetarioPjTable.setRowMargin(5);
        InvetarioPjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InvetarioPjTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(InvetarioPjTable);

        busquedajTextField.setBackground(new java.awt.Color(255, 255, 255));
        busquedajTextField.setForeground(new java.awt.Color(0, 0, 0));

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Nombre de producto");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Ordenar por Categoria");

        categoriaOrdenjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        categoriaOrdenjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaOrdenjComboBoxActionPerformed(evt);
            }
        });

        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        desAscjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ascendente cantidad", "Descendente cantidad", "Ascendente precio", "Descendente precio" }));
        desAscjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desAscjComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(161, 161, 161)
                                .addComponent(jLabel12)
                                .addGap(0, 301, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(busquedajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(categoriaOrdenjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(desAscjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButton3)
                        .addGap(28, 28, 28))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(categoriaOrdenjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3)
                        .addComponent(desAscjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(busquedajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedOtions.addTab("Inventario Productos", jPanel6);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Nombre del Producto");
        jLabel13.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Descripcion");
        jLabel14.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Cantidad Existente");
        jLabel15.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Precio en Quetzales");
        jLabel16.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        nameEditionjTextField.setBackground(new java.awt.Color(0, 204, 204));
        nameEditionjTextField.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        nameEditionjTextField.setForeground(new java.awt.Color(0, 0, 0));

        cantidadEdtionjTextField.setBackground(new java.awt.Color(0, 204, 204));
        cantidadEdtionjTextField.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        cantidadEdtionjTextField.setForeground(new java.awt.Color(0, 0, 0));
        cantidadEdtionjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadEdtionjTextFieldActionPerformed(evt);
            }
        });

        precioEditojTextField.setBackground(new java.awt.Color(0, 204, 204));
        precioEditojTextField.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        precioEditojTextField.setForeground(new java.awt.Color(0, 0, 0));
        precioEditojTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioEditojTextFieldActionPerformed(evt);
            }
        });

        descripEditonjTextArea.setBackground(new java.awt.Color(0, 204, 204));
        descripEditonjTextArea.setColumns(20);
        descripEditonjTextArea.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        descripEditonjTextArea.setForeground(new java.awt.Color(0, 0, 0));
        descripEditonjTextArea.setRows(5);
        jScrollPane4.setViewportView(descripEditonjTextArea);

        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Categorias del Producto");
        jLabel17.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        categoriasProductojComboBox.setForeground(new java.awt.Color(0, 0, 0));

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Agregar Categoria");
        jLabel18.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        categoriaAgregarjComboBox.setForeground(new java.awt.Color(0, 0, 0));
        categoriaAgregarjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        agregarCatejButton.setText("Agregar");
        agregarCatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarCatejButtonActionPerformed(evt);
            }
        });

        actulizarProjButton.setText("Actualizar");
        actulizarProjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actulizarProjButtonActionPerformed(evt);
            }
        });

        eliminarCatjButton.setText("Eliminar Categoria");
        eliminarCatjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarCatjButtonActionPerformed(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(51, 102, 255));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Edicion de Categorias");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane4))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nameEditionjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(categoriasProductojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(actulizarProjButton)
                        .addGap(149, 149, 149))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cantidadEdtionjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(precioEditojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(categoriaAgregarjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(eliminarCatjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(agregarCatejButton)
                .addGap(173, 173, 173))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidadEdtionjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameEditionjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precioEditojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addComponent(actulizarProjButton))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoriasProductojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoriaAgregarjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminarCatjButton)
                    .addComponent(agregarCatejButton))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jTabbedOtions.addTab("Área de Edicion", jPanel8);

        javax.swing.GroupLayout panelOpcionesLayout = new javax.swing.GroupLayout(panelOpciones);
        panelOpciones.setLayout(panelOpcionesLayout);
        panelOpcionesLayout.setHorizontalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addComponent(jTabbedOtions, javax.swing.GroupLayout.PREFERRED_SIZE, 782, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelOpcionesLayout.setVerticalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedOtions, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel2.add(panelOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 780, 630));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Opciones de Producto/Mercancia");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 390, 30));

        jMenu5.setText("Usuarios");

        jMenuItem1.setText("Editar Perfil");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuItem2.setText("Administrar Perfiles");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuBar2.add(jMenu5);

        jMenu7.setText("Ventas");

        jMenuItem4.setText("Nueva Venta");
        jMenu7.add(jMenuItem4);

        jMenuBar2.add(jMenu7);

        jMenu8.setText("Categorias");

        jMenuItem5.setText("sobre categorias");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem5);

        jMenuBar2.add(jMenu8);

        jMenu6.setText("Salir");

        jMenuItem3.setText("Cerrar Secion");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem3);

        jMenuBar2.add(jMenu6);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        if (this.vtnPerfil == null) {
            this.vtnPerfil = new Perfil(this.user, this.userConsul);
        }
        this.vtnPerfil.setLocationRelativeTo(null);
        this.vtnPerfil.setVisible(true);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        if (this.vtnAdminPerfiles == null) {
            this.vtnAdminPerfiles = new FormularioNP(userConsul);
        }
        this.vtnAdminPerfiles.setLocationRelativeTo(null);
        this.vtnAdminPerfiles.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void preciojTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preciojTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preciojTextFieldActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        // TODO add your handling code here:
        if (this.nombrePjTextField.getText().equals("") || this.preciojTextField.getText().equals("") || unidadesjTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Llenar campos obligatorios");
        } else {
            this.productoConsul.insertProducto(new Producto(this.nombrePjTextField.getText(), convertidorInt(this.unidadesjTextField.getText()),
                    this.descjTextArea.getText(), this.convertidorDouble(this.preciojTextField.getText()), categoriaSelect()), insertCategoria());
            manejador.manejadorAgotados(productoConsul.productosAgotados(coeficienteAgotamiento), jTableAgotados);
            manejador.manejoInventarioProductos(productoConsul.listaProductos(true, true), InvetarioPjTable);
            this.nombrePjTextField.setText("");
            this.unidadesjTextField.setText("");
            this.preciojTextField.setText("");
            this.descjTextArea.setText("");
        }

    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jButtonNewCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewCategoriaActionPerformed
        // TODO add your handling code here:
        if (this.formulNC == null) {
            this.formulNC = new FormularioNC(CategoriasjComboBox, categoriaOrdenjComboBox, categoriaAgregarjComboBox, categoriaConsul);
        }
        this.formulNC.setActulizar(false);
        this.formulNC.setLocationRelativeTo(null);
        this.formulNC.setVisible(true);
    }//GEN-LAST:event_jButtonNewCategoriaActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        if (this.formulNC == null) {
            this.formulNC = new FormularioNC(CategoriasjComboBox, categoriaOrdenjComboBox, categoriaAgregarjComboBox, categoriaConsul);
        }
        this.formulNC.setActulizar(false);
        this.formulNC.setLocationRelativeTo(null);
        this.formulNC.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (this.coeficientejTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Mamón, pon un valor en el coeficiente");
        } else {
            this.coeficienteAgotamiento = convertidorInt(this.coeficientejTextField.getText());
            this.manejador.manejadorAgotados(productoConsul.productosAgotados(coeficienteAgotamiento), jTableAgotados);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (this.busquedajTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Llenar campo de busqueda");
        } else {
            manejador.manejoInventarioProductos(this.productoConsul.listaProductos(this.busquedajTextField.getText()), InvetarioPjTable);

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void categoriaOrdenjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaOrdenjComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoriaOrdenjComboBoxActionPerformed

    private void desAscjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desAscjComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desAscjComboBoxActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (categoriaOrdenjComboBox.getSelectedItem().toString().equals("Todos")) {
            manejador.manejoInventarioProductos(productoConsul.listaProductos(isAscendente(), isCantidad()), InvetarioPjTable);
        } else {
            manejador.manejoInventarioProductos(productoConsul.listaProductos(categoriaOrdenjComboBox.getSelectedItem().toString(), isAscendente(), isCantidad()), InvetarioPjTable);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void precioEditojTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioEditojTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioEditojTextFieldActionPerformed

    private void cantidadEdtionjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadEdtionjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadEdtionjTextFieldActionPerformed

    private void agregarCatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarCatejButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarCatejButtonActionPerformed

    private void InvetarioPjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvetarioPjTableMouseClicked
        // TODO add your handling code here:
        int column = this.InvetarioPjTable.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / this.InvetarioPjTable.getRowHeight();
        if (row < this.InvetarioPjTable.getRowCount() && row >= 0 && column < this.InvetarioPjTable.getColumnCount() && column >= 0) {
            Object value = this.InvetarioPjTable.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton btn = (JButton) value;
                producto = productoConsul.productoEdit(btn.getName(), categoriaConsul);
                this.nameEditionjTextField.setText(producto.getNombre());
                this.descripEditonjTextArea.setText(producto.getDescripcion());
                this.cantidadEdtionjTextField.setText(producto.getCantidad() + "");
                this.precioEditojTextField.setText("" + producto.getPrecio());
                categoriaConsul.enlistarCategorias(categoriasProductojComboBox, producto.getCategorias());
                JOptionPane.showMessageDialog(this, "Producto en el área de edicion");
            }
        }
    }//GEN-LAST:event_InvetarioPjTableMouseClicked

    private void actulizarProjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actulizarProjButtonActionPerformed
        // TODO add your handling code here:
        if (producto != null) {
            if (nameEditionjTextField.getText().equals("") || cantidadEdtionjTextField.getText().equals("") || precioEditojTextField.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Llenar los campos obligatorios");
            } else {
                String nameActual = producto.getNombre();
                producto.setCantidad(convertidorInt(cantidadEdtionjTextField.getText()));
                producto.setDescripcion(descripEditonjTextArea.getText());
                producto.setNombre(nameEditionjTextField.getText());
                producto.setPrecio(convertidorDouble(precioEditojTextField.getText()));
                productoConsul.updateProducto(producto, nameActual);
                manejador.manejoInventarioProductos(productoConsul.listaProductos(true, true), InvetarioPjTable);

            }
        }

    }//GEN-LAST:event_actulizarProjButtonActionPerformed

    private void eliminarCatjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarCatjButtonActionPerformed
        // TODO add your handling code here:
        if (producto != null && !categoriasProductojComboBox.getSelectedItem().toString().equals("")) {
            categoriaConsul.deleteCategoriaProducto(producto.getNombre(), categoriasProductojComboBox.getSelectedItem().toString());
 
        }
    }//GEN-LAST:event_eliminarCatjButtonActionPerformed

    private boolean isAscendente() {
        switch (this.desAscjComboBox.getSelectedItem().toString()) {
            case "Ascendente cantidad":
                return true;
            case "Ascendente precio":
                return true;
            default:
                return false;
        }
    }

    private boolean isCantidad() {
        switch (this.desAscjComboBox.getSelectedItem().toString()) {
            case "Ascendente cantidad":
                return true;
            case "Descendente cantidad":
                return true;
            default:
                return false;
        }
    }

    private String categoriaSelect() {
        if (this.CategoriasjComboBox.getSelectedItem().toString().equals("Categorias")) {
            return "";
        } else {
            return this.CategoriasjComboBox.getSelectedItem().toString();
        }
    }

    private boolean insertCategoria() {
        if (this.CategoriasjComboBox.getSelectedItem().toString().equals("Categorias")) {
            return false;
        } else {
            return true;
        }
    }

    private int convertidorInt(String cantidad) {
        int num = 0;
        try {
            num = Integer.parseInt(cantidad);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La cantidad se ha registrado en 0");
        }

        return num;
    }

    private double convertidorDouble(String cantidad) {
        double num = 0.0;
        try {
            num = Double.parseDouble(cantidad);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El precio se ha registrado en 0");
        }

        return num;
    }

    private void soloNumDecimal(JTextField text) {
        text.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c) && c != '.') {
                    e.consume();
                }
                if (c == '.' && text.getText().contains(".")) {
                    e.consume();

                }
            }

        });

    }

    private void soloNum(JTextField text) {
        text.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c)) {
                    e.consume();
                }
            }

        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CategoriasjComboBox;
    private javax.swing.JTable InvetarioPjTable;
    private javax.swing.JButton actulizarProjButton;
    private javax.swing.JButton agregarCatejButton;
    private javax.swing.JTextField busquedajTextField;
    private javax.swing.JTextField cantidadEdtionjTextField;
    private javax.swing.JComboBox<String> categoriaAgregarjComboBox;
    private javax.swing.JComboBox<String> categoriaOrdenjComboBox;
    private javax.swing.JComboBox<String> categoriasProductojComboBox;
    private javax.swing.JTextField coeficientejTextField;
    private javax.swing.JComboBox<String> desAscjComboBox;
    private javax.swing.JTextArea descjTextArea;
    private javax.swing.JTextArea descripEditonjTextArea;
    private javax.swing.JButton eliminarCatjButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonNewCategoria;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedOtions;
    private javax.swing.JTable jTableAgotados;
    private javax.swing.JTextField nameEditionjTextField;
    private javax.swing.JTextField nombrePjTextField;
    private javax.swing.JPanel panelOpciones;
    private javax.swing.JTextField precioEditojTextField;
    private javax.swing.JTextField preciojTextField;
    private javax.swing.JTextField unidadesjTextField;
    // End of variables declaration//GEN-END:variables
}
